### ISSUE TITLE
improve /info/purl for unknown PURLs

### ISSUE THREAD

**Issue by rsteph-de** [ubrostock/purl_server#27]
Der Pfad "/info/purl" zeigt einen Serverfehler (500), wenn die PURL ungültig ist.
Stacktrace:
```
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "purl.domain.path" (template: "purlinfo" - line 39, col 25)
	at org.thymeleaf.spring5.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:292)
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166)
```
Wenn die PURL unbekannt ist, sollte 
1) geprüft werden, ob eine gültige Partial-PURL registriert wurde und dann per temporärem HTTP-Redirect (302) dem Browsesr die entsprechende Seiten-URL übermittelt werden
2) eine "ordentliche Fehlermeldung" ausgegeben werden:
z.B. "Die PURL xy wurde nicht auf dem PURL-Server registriert"
Meinetwegen kann das auch auch "404 - Not found" Fehler sein.

Der Pfad /json/purl sollte sich auf die gleiche Weise verhalten.

**Comment by rsteph-de** [comment]
Für den Fall, dass die PURL nicht vorhanden ist, sollte der Stacktrace nicht angezeigt werden.
```
org.springframework.web.server.ResponseStatusException: 404 NOT_FOUND "PURL nicht gefunden!"
	at de.uni.rostock.ub.purl_server.info.controller.PurlInfoController.retrieveInfoPurl(PurlInfoController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

Vermutlich können wir prüfen, ob es sich um eine `ResponseStatusException` handelt.
(Nochmal prüfen, ob wir diese Exception auch in anderen Fällen verwenden).
Und dann den Stacktrace-Bereich im View für die Fehlerseite ausblenden.

Ideee: Im View `error.html` prüfen, ob die Variable `${exception}` den Wert  `ResponseStatusException`  enthält und dann mit `th:if`  steuern, ob der Stacktrace angezeigt werden soll.
