### ISSUE TITLE
Server error domain search

### ISSUE THREAD

**Issue by rsteph-de** [ubrostock/purl_server#5]
Wenn man das Formular zur Domain-Suche leer lässt erscheint folgende Fehlermeldung:

```
> There was an unexpected error (type=Internal Server Error, status=500).
> PreparedStatementCallback; bad SQL grammar [SELECT d.*, u.* FROM user u, domain d, domainuser du WHERE du.user_id = du.domain_id AND (path LIKE ?) AND (d.status < ?) AND (name LIKE ?) AND (login LIKE ?) GROUP BY d.id ORDER BY d.path LIMIT 50;]; nested exception is java.sql.SQLSyntaxErrorException: Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'purl_server.u.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
> org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT d.*, u.* FROM user u, domain d, domainuser du WHERE du.user_id = du.domain_id AND (path LIKE ?) AND (d.status < ?) AND (name LIKE ?) AND (login LIKE ?) GROUP BY d.id ORDER BY d.path LIMIT 50;]; nested exception is java.sql.SQLSyntaxErrorException: Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'purl_server.u.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
> 	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:93)
> 	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
> 	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
> 	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
> 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
> 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
> 
```

**Comment by rsteph-de** [comment]
Das Problem enstand mit MySQL 8, wo alle Spalten für ein GROUP-By alle Spalten im SELECT vorkommen müssen

> SQLSyntaxErrorException:
> Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'purl_server.u.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

Bitte auch nochmal alle anderen SELECT-Statements mit GROUP-BY auf dieses Problem untersuchen.
